---
- name: 'Baixa o arquivo de intalacao do wordpress'
  get_url:
    url: 'https://wordpress.org/wordpress-5.1.4.tar.gz'
    dest: /tmp/wordpress.tar.gz

- name: 'Descompacta o arquivo'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Configura o wp-config com as entradas do bd'
  template:
    src: 'templates/wp-config.php.j2'
    dest: '{{ wp_installation_dir }}/wp-config.php'
  become: yes

- name: 'Configura o apache para servir o wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache